.in
.decl Arc(y:number, x:number)
.input Arc.csv

.decl Source(x:number)
.input Source.csv

.printsize
.decl BipartiteViolation(x:number)
.decl Zero(x:number)
.decl One(x:number)
.decl BiArc(x: number, y: number)

.rule
BiArc(x, y) :- Arc(x, y).
BiArc(x, y) :- Arc(y, x).

Zero(x) :- Source(x).
One(y) :- BiArc(x, y), Zero(x).
Zero(y) :- BiArc(x, y), One(x).
BipartiteViolation(x) :- One(x), Zero(x).