EDB_DECL:
addressOf(y: number, x: number)
assign(y: number, x: number)
load(y: number, x: number)
store(y: number, x: number)

IDB_DECL:
pointsTo(y: number, x: number)

RULE_DECL:
pointsTo(y, x) :-
 addressOf(y, x).

pointsTo(y, x) :-
 assign(y, z),
 pointsTo(z, x).

pointsTo(y, w) :-
 load(y, x),
 pointsTo(x, z),
 pointsTo(z, w).

pointsTo(z, w) :-
 store(y, x),
 pointsTo(y, z),
 pointsTo(x, w).
