EDB_DECL:
DirectSuperclass(class int, superclass int)
DirectSuperinterface(ref int, interface int)
MainClass(class int)
FormalParam(index int, method int, var int)
ComponentType(arrayType int, componentType int)
AssignReturnValue(invocation int, to int)
ActualParam(index int, invocation int, var int)
Method_Modifier(mod int, method int)
Var_Type(var int, type int)
HeapAllocation_Type(heap int, type int)
_ClassType(class int)
_ArrayType(arrayType int)
_InterfaceType(interface int)
_Var_DeclaringMethod(var int, method int)
_ApplicationClass(type int)
_ThisVar(method int, var int)
_NormalHeap(id int, type int)
_StringConstant(id int)
_AssignHeapAllocation(instruction int, index int, heap int, to int, inmethod int, linenumber int)
_AssignLocal(instruction int, index int, from int, to int, inmethod int)
_AssignCast(instruction int, index int, from int, to int, type int, inmethod int)
_Field(signature int, declaringClass int, simplename int, type int)
_StaticMethodInvocation(instruction int, index int, signature int, method int)
_SpecialMethodInvocation(instruction int, index int, signature int, base int, method int)
_VirtualMethodInvocation(instruction int, index int, signature int, base int, method int)
_Method(method int, simplename int, params int, declaringType int, returnType int, jvmDescriptor int, arity int)
Method_Descriptor(method int, descriptor int)
_StoreInstanceField(instruction int, index int, from int, base int, signature int, method int)
_LoadInstanceField(instruction int, index int, to int, base int, signature int, method int)
_StoreStaticField(instruction int, index int, from int, signature int, method int)
_LoadStaticField(instruction int, index int, to int, signature int, method int)
_StoreArrayIndex(instruction int, index int, from int, base int, method int)
_LoadArrayIndex(instruction int, index int, to int, base int, method int)
_Return(instruction int, index int, var int, method int)

IDB_DECL:
isType(t int)
isReferenceType(t int)
isArrayType(t int)
isClassType(t int)
isInterfaceType(t int)
ApplicationClass(ref int)
Field_DeclaringType(field int, declaringClass int)
Method_DeclaringType(method int, declaringType int)
Method_ReturnType(method int, returnType int)
Method_SimpleName(method int, simpleName int)
Method_Params(method int, params int)
ThisVar(method int, var int)
Var_DeclaringMethod(var int, method int)
Instruction_Method(insn int, inMethod int)
isVirtualMethodInvocation_Insn(insn int)
isStaticMethodInvocation_Insn(insn int)
FieldInstruction_Signature(insn int, sign int)
LoadInstanceField_Base(insn int, var int)
LoadInstanceField_To(insn int, var int)
StoreInstanceField_From(insn int, var int)
StoreInstanceField_Base(insn int, var int)
LoadStaticField_To(insn int, var int)
StoreStaticField_From(insn int, var int)
LoadArrayIndex_Base(insn int, var int)
LoadArrayIndex_To(insn int, var int)
StoreArrayIndex_From(insn int, var int)
StoreArrayIndex_Base(insn int, var int)
AssignInstruction_To(insn int, to int)
AssignCast_From(insn int, from int)
AssignCast_Type(insn int, type int)
AssignLocal_From(insn int, from int)
AssignHeapAllocation_Heap(insn int, heap int)
ReturnNonvoid_Var(return int, var int)
MethodInvocation_Method(invocation int, signature int)
VirtualMethodInvocation_Base(invocation int, base int)
VirtualMethodInvocation_SimpleName(invocation int, simplename int)
VirtualMethodInvocation_Descriptor(invocation int, descriptor int)
SpecialMethodInvocation_Base(invocation int, base int)
MethodInvocation_Base(invocation int, base int)
LoadInstanceField(base int, sig int, to int, inmethod int)
StoreInstanceField(from int, base int, signature int, inmethod int)
LoadStaticField(sig int, to int, inmethod int)
StoreStaticField(from int, signature int, inmethod int)
LoadArrayIndex(base int, to int, inmethod int)
StoreArrayIndex(from int, base int, inmethod int)
AssignCast(type int, from int, to int, inmethod int)
AssignLocal(from int, to int, inmethod int)
AssignHeapAllocation(heap int, to int, inmethod int)
ReturnVar(var int, method int)
StaticMethodInvocation(invocation int, signature int, inmethod int)
MethodLookup(simplename int, descriptor int, type int, method int)
MethodImplemented(simplename int, descriptor int, type int, method int)
DirectSubclass(a int, c int)
Subclass(c int, a int)
Superclass(c int, a int)
Superinterface(k int, c int)
SubtypeOf(subtype int, type int)
SupertypeOf(supertype int, type int)
SubtypeOfDifferent(subtype int, type int)
MainMethodDeclaration(method int)
ClassInitializer(type int, method int)
InitializedClass(classOrInterface int)
Assign(to int, from int)
VarPointsTo(heap int, var int)
InstanceFieldPointsTo(heap int, fld int, baseheap int)
StaticFieldPointsTo(heap int, fld int)
CallGraphEdge(invocation int, meth int)
ArrayIndexPointsTo(baseheap int, heap int)
Reachable(method int)

RULE_DECL:
isType(class) :- _ClassType(class).
isReferenceType(class) :- _ClassType(class).
isClassType(class) :- _ClassType(class).
isType(arrayType) :- _ArrayType(arrayType).
isReferenceType(arrayType) :- _ArrayType(arrayType).
isArrayType(arrayType) :- _ArrayType(arrayType).
isType(interface) :- _InterfaceType(interface).
isReferenceType(interface) :- _InterfaceType(interface).
isInterfaceType(interface) :- _InterfaceType(interface).
Var_DeclaringMethod(var, method) :- _Var_DeclaringMethod(var, method).
isType(type) :- _ApplicationClass(type).
isReferenceType(type) :- _ApplicationClass(type).
ApplicationClass(type) :- _ApplicationClass(type).
ThisVar(method, var) :- _ThisVar(method, var).
isType(type) :- _NormalHeap(_, type).
Instruction_Method(instruction, method) :- _AssignHeapAllocation(instruction, index, heap, to, method, linenumber).
AssignInstruction_To(instruction, to) :- _AssignHeapAllocation(instruction, index, heap, to, method, linenumber).
AssignHeapAllocation_Heap(instruction, heap) :- _AssignHeapAllocation(instruction, index, heap, to, method, linenumber).
Instruction_Method(instruction, method) :- _AssignLocal(instruction, index, from, to, method).
AssignLocal_From(instruction, from) :- _AssignLocal(instruction, index, from, to, method).
AssignInstruction_To(instruction, to) :- _AssignLocal(instruction, index, from, to, method).
Instruction_Method(instruction, method) :- _AssignCast(instruction, index, from, to, type, method).
AssignCast_Type(instruction, type) :- _AssignCast(instruction, index, from, to, type, method).
AssignCast_From(instruction, from) :- _AssignCast(instruction, index, from, to, type, method).
AssignInstruction_To(instruction, to) :- _AssignCast(instruction, index, from, to, type, method).
Field_DeclaringType(signature, declaringType) :- _Field(signature, declaringType, _, _).
MethodInvocation_Base(invocation, base) :- VirtualMethodInvocation_Base(invocation, base).
MethodInvocation_Base(invocation, base) :- SpecialMethodInvocation_Base(invocation, base).
Instruction_Method(instruction, method) :- _StaticMethodInvocation(instruction, index, signature, method).
isStaticMethodInvocation_Insn(instruction) :- _StaticMethodInvocation(instruction, index, signature, method).
MethodInvocation_Method(instruction, signature) :- _StaticMethodInvocation(instruction, index, signature, method).
Instruction_Method(instruction, method) :- _SpecialMethodInvocation(instruction, index, signature, base, method).
SpecialMethodInvocation_Base(instruction, base) :- _SpecialMethodInvocation(instruction, index, signature, base, method).
MethodInvocation_Method(instruction, signature) :- _SpecialMethodInvocation(instruction, index, signature, base, method).
Instruction_Method(instruction, method) :- _VirtualMethodInvocation(instruction, index, signature, base, method).
isVirtualMethodInvocation_Insn(instruction) :- _VirtualMethodInvocation(instruction, index, signature, base, method).
VirtualMethodInvocation_Base(instruction, base) :- _VirtualMethodInvocation(instruction, index, signature, base, method).
MethodInvocation_Method(instruction, signature) :- _VirtualMethodInvocation(instruction, index, signature, base, method).
Method_SimpleName(method, simplename) :- _Method(method, simplename, params, declaringType, returnType, jvmDescriptor, arity).
Method_DeclaringType(method, declaringType) :- _Method(method, simplename, params, declaringType, returnType, jvmDescriptor, arity).
Instruction_Method(instruction, method) :- _StoreInstanceField(instruction, index, from, base, signature, method).
FieldInstruction_Signature(instruction, signature) :- _StoreInstanceField(instruction, index, from, base, signature, method).
StoreInstanceField_Base(instruction, base) :- _StoreInstanceField(instruction, index, from, base, signature, method).
StoreInstanceField_From(instruction, from) :- _StoreInstanceField(instruction, index, from, base, signature, method).
Instruction_Method(instruction, method) :- _LoadInstanceField(instruction, index, to, base, signature, method).
FieldInstruction_Signature(instruction, signature) :- _LoadInstanceField(instruction, index, to, base, signature, method).
LoadInstanceField_Base(instruction, base) :- _LoadInstanceField(instruction, index, to, base, signature, method).
LoadInstanceField_To(instruction, to) :- _LoadInstanceField(instruction, index, to, base, signature, method).
Instruction_Method(instruction, method) :- _StoreStaticField(instruction, index, from, signature, method).
FieldInstruction_Signature(instruction, signature) :- _StoreStaticField(instruction, index, from, signature, method).
StoreStaticField_From(instruction, from) :- _StoreStaticField(instruction, index, from, signature, method).
Instruction_Method(instruction, method) :- _LoadStaticField(instruction, index, to, signature, method).
FieldInstruction_Signature(instruction, signature) :- _LoadStaticField(instruction, index, to, signature, method).
LoadStaticField_To(instruction, to) :- _LoadStaticField(instruction, index, to, signature, method).
Instruction_Method(instruction, method) :- _StoreArrayIndex(instruction, index, from, base, method).
StoreArrayIndex_Base(instruction, base) :- _StoreArrayIndex(instruction, index, from, base, method).
StoreArrayIndex_From(instruction, from) :- _StoreArrayIndex(instruction, index, from, base, method).
Instruction_Method(instruction, method) :- _LoadArrayIndex(instruction, index, to, base, method).
LoadArrayIndex_Base(instruction, base) :- _LoadArrayIndex(instruction, index, to, base, method).
LoadArrayIndex_To(instruction, to) :- _LoadArrayIndex(instruction, index, to, base, method).
Instruction_Method(instruction, method) :- _Return(instruction, index, var, method).
ReturnNonvoid_Var(instruction, var) :- _Return(instruction, index, var, method).
LoadInstanceField(base, sig, to, inmethod) :- Instruction_Method(insn, inmethod), LoadInstanceField_Base(insn, base), FieldInstruction_Signature(insn, sig), LoadInstanceField_To(insn, to).
StoreInstanceField(from, base, sig, inmethod) :- Instruction_Method(insn, inmethod), StoreInstanceField_From(insn, from), StoreInstanceField_Base(insn, base), FieldInstruction_Signature(insn, sig).
LoadStaticField(sig, to, inmethod) :- Instruction_Method(insn, inmethod), FieldInstruction_Signature(insn, sig), LoadStaticField_To(insn, to).
StoreStaticField(from, sig, inmethod) :- Instruction_Method(insn, inmethod), StoreStaticField_From(insn, from), FieldInstruction_Signature(insn, sig).
LoadArrayIndex(base, to, inmethod) :- Instruction_Method(insn, inmethod), LoadArrayIndex_Base(insn, base), LoadArrayIndex_To(insn, to).
StoreArrayIndex(from, base, inmethod) :- Instruction_Method(insn, inmethod), StoreArrayIndex_From(insn, from), StoreArrayIndex_Base(insn, base).
AssignCast(type, from, to, inmethod) :- Instruction_Method(insn, inmethod), AssignCast_From(insn, from), AssignInstruction_To(insn, to), AssignCast_Type(insn, type).
AssignLocal(from, to, inmethod) :- AssignInstruction_To(insn, to), Instruction_Method(insn, inmethod), AssignLocal_From(insn, from).
AssignHeapAllocation(heap, to, inmethod) :- Instruction_Method(insn, inmethod), AssignHeapAllocation_Heap(insn, heap), AssignInstruction_To(insn, to).
ReturnVar(var, method) :- Instruction_Method(insn, method), ReturnNonvoid_Var(insn, var).
StaticMethodInvocation(invocation, signature, inmethod) :- isStaticMethodInvocation_Insn(invocation), Instruction_Method(invocation, inmethod), MethodInvocation_Method(invocation, signature).
VirtualMethodInvocation_SimpleName(invocation, simplename) :- isVirtualMethodInvocation_Insn(invocation), MethodInvocation_Method(invocation, signature), Method_SimpleName(signature, simplename), Method_Descriptor(signature, descriptor).
VirtualMethodInvocation_Descriptor(invocation, descriptor) :- isVirtualMethodInvocation_Insn(invocation), MethodInvocation_Method(invocation, signature), Method_SimpleName(signature, simplename), Method_Descriptor(signature, descriptor).
MethodLookup(simplename, descriptor, type, method) :- MethodImplemented(simplename, descriptor, type, method).
MethodLookup(simplename, descriptor, type, method) :- DirectSuperclass(type, supertype), MethodLookup(simplename, descriptor, supertype, method), !MethodImplemented(simplename, descriptor, type, _).
MethodLookup(simplename, descriptor, type, method) :- DirectSuperinterface(type, supertype), MethodLookup(simplename, descriptor, supertype, method), !MethodImplemented(simplename, descriptor, type, _).
MethodImplemented(simplename, descriptor, type, method) :- Method_SimpleName(method, simplename), Method_Descriptor(method, descriptor), Method_DeclaringType(method, type), !Method_Modifier(779558, method).
MainMethodDeclaration(method) :- MainClass(type), Method_DeclaringType(method, type), method != 1045470, method != 2357714, method != 1614718, Method_SimpleName(method, 780495), Method_Descriptor(method, 5097637), Method_Modifier(1347650, method), Method_Modifier(1347648, method).
DirectSubclass(a, c) :- DirectSuperclass(a, c).
Subclass(c, a) :- DirectSubclass(a, c).
Subclass(c, a) :- Subclass(b, a), DirectSubclass(b, c).
Superclass(c, a) :- Subclass(a, c).
Superinterface(k, c) :- DirectSuperinterface(c, k).
Superinterface(k, c) :- DirectSuperinterface(c, j), Superinterface(k, j).
Superinterface(k, c) :- DirectSuperclass(c, super), Superinterface(k, super).
SubtypeOf(s, s) :- isClassType(s).
SubtypeOf(t, t) :- isType(t).
SubtypeOf(s, t) :- Subclass(t, s).
SubtypeOf(s, s) :- isInterfaceType(s).
SubtypeOf(s, t) :- isClassType(s), Superinterface(t, s).
SubtypeOf(s, t) :- isInterfaceType(s), isType(t), t = 1168277.
SubtypeOf(s, t) :- isArrayType(s), isType(t), t = 1168277.
SubtypeOf(s, t) :- isInterfaceType(s), Superinterface(t, s).
SubtypeOf(s, t) :- SubtypeOf(sc, tc), ComponentType(s, sc), ComponentType(t, tc), isReferenceType(sc), isReferenceType(tc).
SubtypeOf(s, t) :- isArrayType(s), isInterfaceType(t), isType(t), t = 1875761.
SubtypeOf(s, t) :- isArrayType(s), isInterfaceType(t), isType(t), t = 1132248.
SupertypeOf(s, t) :- SubtypeOf(t, s).
SubtypeOfDifferent(s, t) :- SubtypeOf(s, t), s != t.
ClassInitializer(type, method) :- MethodImplemented(1386348, 5096596, type, method).
InitializedClass(superclass) :- InitializedClass(class), DirectSuperclass(class, superclass).
InitializedClass(superinterface) :- InitializedClass(classOrInterface), DirectSuperinterface(classOrInterface, superinterface).
InitializedClass(class) :- MainMethodDeclaration(method), Method_DeclaringType(method, class).
InitializedClass(class) :- Reachable(inmethod), AssignHeapAllocation(heap, _, inmethod), HeapAllocation_Type(heap, class).
InitializedClass(class) :- Reachable(inmethod), Instruction_Method(invocation, inmethod), isStaticMethodInvocation_Insn(invocation), MethodInvocation_Method(invocation, signature), Method_DeclaringType(signature, class).
InitializedClass(classOrInterface) :- Reachable(inmethod), StoreStaticField(_, signature, inmethod), Field_DeclaringType(signature, classOrInterface).
InitializedClass(classOrInterface) :- Reachable(inmethod), LoadStaticField(signature, _, inmethod), Field_DeclaringType(signature, classOrInterface).
Reachable(clinit) :- InitializedClass(class), ClassInitializer(class, clinit).
Assign(actual, formal) :- CallGraphEdge(invocation, method), FormalParam(index, method, formal), ActualParam(index, invocation, actual).
Assign(return, local) :- CallGraphEdge(invocation, method), ReturnVar(return, method), AssignReturnValue(invocation, local).
VarPointsTo(heap, var) :- AssignHeapAllocation(heap, var, inMethod), Reachable(inMethod).
VarPointsTo(heap, to) :- Assign(from, to), VarPointsTo(heap, from).
VarPointsTo(heap, to) :- Reachable(inmethod), AssignLocal(from, to, inmethod), VarPointsTo(heap, from).
VarPointsTo(heap, to) :- Reachable(inmethod), AssignCast(type, from, to, inmethod), SupertypeOf(type, heaptype), HeapAllocation_Type(heap, heaptype), VarPointsTo(heap, from).
ArrayIndexPointsTo(baseheap, heap) :- Reachable(inmethod), StoreArrayIndex(from, base, inmethod), VarPointsTo(baseheap, base), VarPointsTo(heap, from), HeapAllocation_Type(heap, heaptype), HeapAllocation_Type(baseheap, baseheaptype), ComponentType(baseheaptype, componenttype), SupertypeOf(componenttype, heaptype).
VarPointsTo(heap, to) :- Reachable(inmethod), LoadArrayIndex(base, to, inmethod), VarPointsTo(baseheap, base), ArrayIndexPointsTo(baseheap, heap), Var_Type(to, type), HeapAllocation_Type(baseheap, baseheaptype), ComponentType(baseheaptype, basecomponenttype), SupertypeOf(type, basecomponenttype).
VarPointsTo(heap, to) :- Reachable(inmethod), LoadInstanceField(base, signature, to, inmethod), VarPointsTo(baseheap, base), InstanceFieldPointsTo(heap, signature, baseheap).
VarPointsTo(heap, to) :- Reachable(inmethod), LoadStaticField(fld, to, inmethod), StaticFieldPointsTo(heap, fld).
VarPointsTo(heap, this) :- Reachable(inMethod), Instruction_Method(invocation, inMethod), VirtualMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), HeapAllocation_Type(heap, heaptype), VirtualMethodInvocation_SimpleName(invocation, simplename), VirtualMethodInvocation_Descriptor(invocation, descriptor), MethodLookup(simplename, descriptor, heaptype, toMethod), ThisVar(toMethod, this).
InstanceFieldPointsTo(heap, fld, baseheap) :- Reachable(inmethod), StoreInstanceField(from, base, fld, inmethod), VarPointsTo(heap, from), VarPointsTo(baseheap, base).
StaticFieldPointsTo(heap, fld) :- Reachable(inmethod), StoreStaticField(from, fld, inmethod), VarPointsTo(heap, from).
Reachable(toMethod) :- Reachable(inMethod), Instruction_Method(invocation, inMethod), VirtualMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), HeapAllocation_Type(heap, heaptype), VirtualMethodInvocation_SimpleName(invocation, simplename), VirtualMethodInvocation_Descriptor(invocation, descriptor), MethodLookup(simplename, descriptor, heaptype, toMethod).
CallGraphEdge(invocation, toMethod) :- Reachable(inMethod), Instruction_Method(invocation, inMethod), VirtualMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), HeapAllocation_Type(heap, heaptype), VirtualMethodInvocation_SimpleName(invocation, simplename), VirtualMethodInvocation_Descriptor(invocation, descriptor), MethodLookup(simplename, descriptor, heaptype, toMethod).
Reachable(tomethod) :- Reachable(inmethod), StaticMethodInvocation(invocation, tomethod, inmethod).
CallGraphEdge(invocation, tomethod) :- Reachable(inmethod), StaticMethodInvocation(invocation, tomethod, inmethod).
Reachable(tomethod) :- Reachable(inmethod), Instruction_Method(invocation, inmethod), SpecialMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), MethodInvocation_Method(invocation, tomethod), ThisVar(tomethod, this).
CallGraphEdge(invocation, tomethod) :- Reachable(inmethod), Instruction_Method(invocation, inmethod), SpecialMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), MethodInvocation_Method(invocation, tomethod), ThisVar(tomethod, this).
VarPointsTo(heap, this) :- Reachable(inmethod), Instruction_Method(invocation, inmethod), SpecialMethodInvocation_Base(invocation, base), VarPointsTo(heap, base), MethodInvocation_Method(invocation, tomethod), ThisVar(tomethod, this).
Reachable(method) :- MainMethodDeclaration(method).