EDB_DECL:
Assign(x int, y int)
Dereference(x int, y int)

IDB_DECL:
ValueFlow(x int, y int)
MemoryAlias(x int, y int)
ValueAlias(x int, y int)

RULE_DECL:
ValueFlow(y, x) :- Assign(y, x).
ValueFlow(x, y) :- Assign(x, z), MemoryAlias(z, y).
ValueFlow(x, y) :- ValueFlow(x, z), ValueFlow(z, y).
MemoryAlias(x, w) :- Dereference(y, x), ValueAlias(y, z), Dereference(z, w).
ValueAlias(x, y) :- ValueFlow(z, x), ValueFlow(z, y).
ValueAlias(x, y) :- MemoryAlias(z, w), ValueFlow(w, y), ValueFlow(z, x).
ValueFlow(x, x) :- Assign(x, y).
ValueFlow(x, x) :- Assign(y, x).
MemoryAlias(x, x) :- Assign(y, x).
MemoryAlias(x, x) :- Assign(x, y).