EDB_DECL:
Arch_memory_access(AccessType int, EA int, DirectReg int, BaseReg int, IndexReg int, Offset int)
Arch_reg_reg_arithmetic_operation(EA int, Dst int, Src1 int, Src2 int, Mult int, Offset int)
Arch_return_reg(Reg int)
Block_next(Block int, BlockEnd int, NextBlock int)
Block_last_instruction(Block int, EA int)
Code_in_block(EA int, Block int)
Direct_call(EA int, Dest int)
May_fallthrough(o int, d int)
Reg_def_use_block_last_def(EA int, EA_def int, Var int)
Reg_def_use_defined_in_block(Block int, Var int)
Reg_def_use_flow_def(EA int, Var int, EA_next int, Value int)
Reg_def_use_live_var_def(Block int, VarIdentity int, LiveVar int, EA_def int)
Reg_def_use_ref_in_block(Block int, Var int)
Reg_def_use_return_block_end(Callee int, CalleeEnd int, Block int, BlockEnd int)
Reg_def_use_used(EA int, Var int, Index int)
Reg_def_use_used_in_block(Block int, EA_used int, Var int, Index int)
Reg_used_for(EA int, Reg int, Type int)
Relative_jump_table_entry_candidate(EA int, TableStart int, Size int, Reference int, Dest int, Scale int, Offset int)
Stack_def_use_def(EA int, VarReg int, VarPos int)
Stack_def_use_defined_in_block(Block int, VarReg int, VarPos int)
Stack_def_use_live_var_def(Block int, VarIdentityReg int, VarIdentityPos int, LiveVarReg int, LiveVarPos int, EA_def int)
Stack_def_use_ref_in_block(Block int, VarReg int, VarPos int)
Stack_def_use_used_in_block(Block int, EA_used int, VarReg int, VarPos int, Index int)
Stack_def_use_used(EA int, VarReg int, VarPos int, Index int)
Stack_def_use_live_var_used(Block int, LiveVarReg int, LiveVarPos int, UsedVarReg int, UsedVarPos int, EA_used int, Index int, Moves int)
Jump_table_start(EA_jump int, Size int, TableStart int, TableRef int, Scale int)
def_used_for_address_0(EA_def int, Reg int, Type int)
Stack_def_use_block_last_def(EA int, EA_def int, VarReg int, VarPos int)

IDB_DECL:
Stack_def_use_def_used(EA_def int, VarDefReg int, VarDefPos int, EA_used int, VarUsedReg int, VarUsedPos int)
Reg_def_use_return_val_used(EA_call int, Callee int, Reg int, EA_used int, Index_used int)
Reg_def_use_live_var_used(Block int, LiveVar int, EA_used int, Index int)
Jump_table_target(EA int, Dest int)
Reg_def_use_def_used(EA_def int, Var int, EA_used int, Index_used int)
Reg_def_use_live_var_at_prior_used(EA_used int, BlockUsed int, Var int)
Reg_def_use_live_var_at_block_end(Block int, BlockUsed int, Var int)
Reg_reg_arithmetic_operation_defs(EA int, Reg_def int, EA_def1 int, Reg1 int, EA_def2 int, Reg2 int, Mult int, Offset int)
Def_used_for_address(EA_def int, Reg int, Type int)
Stack_def_use_live_var_at_block_end(Block int, BlockUsed int, VarReg int, VarPos int)
Stack_def_use_live_var_at_prior_used(EA_used int, BlockUsed int, VarReg int, VarPos int)

RULE_DECL:
Jump_table_target(EA,Dest) :- Jump_table_start(EA,Size,TableStart,_,_), Relative_jump_table_entry_candidate(_,TableStart,Size,_,Dest,_,_).
Reg_def_use_def_used(EA_def,Var,EA_used,Index) :- Reg_def_use_used(EA_used,Var,Index), Reg_def_use_block_last_def(EA_used,EA_def,Var).
Reg_def_use_def_used(EA_def,VarIdentity,EA_used,Index) :- Reg_def_use_live_var_at_block_end(Block,BlockUsed,Var), Reg_def_use_live_var_def(Block,VarIdentity,Var,EA_def), Reg_def_use_live_var_used(BlockUsed,Var,EA_used,Index).
Reg_def_use_def_used(EA_def,Var,Next_EA_used,NextIndex) :- Reg_def_use_live_var_at_prior_used(EA_used,NextUsedBlock,Var), Reg_def_use_def_used(EA_def,Var,EA_used,_), Reg_def_use_live_var_used(NextUsedBlock,Var,Next_EA_used,NextIndex).
Reg_def_use_def_used(EA_def,Reg,EA_used,Index) :- Reg_def_use_return_val_used(_,Callee,Reg,EA_used,Index), Reg_def_use_return_block_end(Callee,_,_,BlockEnd), Reg_def_use_block_last_def(BlockEnd,EA_def,Reg).
Reg_def_use_return_val_used(EA_call,Callee,Reg,EA_used,Index_used) :- Arch_return_reg(Reg), Reg_def_use_def_used(EA_call,Reg,EA_used,Index_used), Direct_call(EA_call,Callee).
Reg_def_use_live_var_used(Block,Var,EA_used,Index) :- Reg_def_use_used_in_block(Block,EA_used,Var,Index), !Reg_def_use_block_last_def(EA_used,_,Var).
Reg_def_use_live_var_used(RetBlock,Reg,EA_used,Index) :- Reg_def_use_return_block_end(Callee,_,RetBlock,RetBlockEnd), !Reg_def_use_block_last_def(RetBlockEnd,_,Reg), Reg_def_use_return_val_used(_,Callee,Reg,EA_used,Index).
Reg_def_use_live_var_at_prior_used(EA_used,BlockUsed,Var) :- Reg_def_use_live_var_at_block_end(Block,BlockUsed,Var), Reg_def_use_used_in_block(Block,EA_used,Var,_), !Reg_def_use_defined_in_block(Block,Var).
Reg_def_use_live_var_at_block_end(PrevBlock,Block,Var) :- Block_next(PrevBlock,PrevBlockEnd,Block), Reg_def_use_live_var_used(Block,Var,_,_), !Reg_def_use_flow_def(PrevBlockEnd,Var,Block,_).
Reg_def_use_live_var_at_block_end(PrevBlock,BlockUsed,Var) :- Reg_def_use_live_var_at_block_end(Block,BlockUsed,Var), !Reg_def_use_ref_in_block(Block,Var), Block_next(PrevBlock,_,Block).
Reg_reg_arithmetic_operation_defs(EA,Reg_def,EA_def1,Reg1,EA_def2,Reg2,Mult,Offset) :- Def_used_for_address(EA,Reg_def,_), Arch_reg_reg_arithmetic_operation(EA,Reg_def,Reg1,Reg2,Mult,Offset), Reg1 != Reg2, Reg_def_use_def_used(EA_def1,Reg1,EA,_), EA != EA_def1, Reg_def_use_def_used(EA_def2,Reg2,EA,_), EA != EA_def2.
Def_used_for_address(EA,Reg,Type) :- def_used_for_address_0(EA,Reg,Type), Type = 371929.
Def_used_for_address(EA_def,Reg,Type) :- Reg_def_use_def_used(EA_def,Reg,EA,_), Reg_used_for(EA,Reg,Type).
Def_used_for_address(EA_def,Reg,Type) :- Def_used_for_address(EA_used,_,Type), Reg_def_use_def_used(EA_def,Reg,EA_used,_).
Def_used_for_address(EA_def,Reg1,Type) :- Def_used_for_address(EALoad,Reg2,Type), Arch_memory_access(332573,EALoad,Reg2,RegBaseLoad,332575,StackPosLoad), Stack_def_use_def_used(EAStore,RegBaseStore,StackPosStore,EALoad,RegBaseLoad,StackPosLoad), Arch_memory_access(333071,EAStore,Reg1,RegBaseStore,332575,StackPosStore), Reg_def_use_def_used(EA_def,Reg1,EAStore,_).
Stack_def_use_def_used(EA_def,Varr,Varp,EA_used,Varr,Varp) :- Stack_def_use_used(EA_used,Varr,Varp,_), Stack_def_use_block_last_def(EA_used,EA_def,Varr,Varp).
Stack_def_use_def_used(EA_def,DefVarr,DefVarp,EA_used,VarUsedr,VarUsedp) :- Stack_def_use_live_var_at_block_end(Block,BlockUsed,Varr,Varp), Stack_def_use_live_var_def(Block,DefVarr,DefVarp,Varr,Varp,EA_def), Stack_def_use_live_var_used(BlockUsed,Varr,Varp,VarUsedr,VarUsedp,EA_used,_,_).
Stack_def_use_def_used(EA_def,DefVarr,DefVarp,EA_used,UsedVarr,UsedVarp) :- Stack_def_use_live_var_used(EA,DefVarr,DefVarp,UsedVarr,UsedVarp,EA_used,_,_), May_fallthrough(EA_def,EA), Code_in_block(EA_def,Block), Code_in_block(EA,Block), Stack_def_use_def(EA_def,DefVarr,DefVarp).
Stack_def_use_def_used(EA_def,VarDefr,VarDefp,Next_EA_used,VarUsedr,VarUsedp) :- Stack_def_use_live_var_at_prior_used(EA_used,NextUsedBlock,Varr,Varp), Stack_def_use_def_used(EA_def,VarDefr,VarDefp,EA_used,Varr,Varp), Stack_def_use_live_var_used(NextUsedBlock,Varr,Varp,VarUsedr,VarUsedp,Next_EA_used,_,_).
Stack_def_use_live_var_at_block_end(PrevBlock,BlockUsed,inlined_BaseReg_374,inlined_StackPos_374) :- Stack_def_use_live_var_at_block_end(Block,BlockUsed,inlined_BaseReg_374,inlined_StackPos_374), !Stack_def_use_ref_in_block(Block,inlined_BaseReg_374,inlined_StackPos_374), !Reg_def_use_defined_in_block(Block,inlined_BaseReg_374), Block_next(PrevBlock,_,Block).
Stack_def_use_live_var_at_block_end(PrevBlock,Block,Varr,Varp) :- Block_next(PrevBlock,_,Block), Stack_def_use_live_var_used(Block,Varr,Varp,_,_,_,_,_).
Stack_def_use_live_var_at_prior_used(EA_used,BlockUsed,inlined_BaseReg_375,inlined_StackPos_375) :- Stack_def_use_live_var_at_block_end(Block,BlockUsed,inlined_BaseReg_375,inlined_StackPos_375), Stack_def_use_used_in_block(Block,EA_used,inlined_BaseReg_375,inlined_StackPos_375,_), !Reg_def_use_defined_in_block(Block,inlined_BaseReg_375), !Stack_def_use_defined_in_block(Block,inlined_BaseReg_375,inlined_StackPos_375).