
.decl NullEdge(x: number, y: number)
.input NullEdge(IO="file", filename="NullEdge.csv", delimiter=",")

.decl Edge(x: number, y: number)
.input Edge(IO="file", filename="Edge.csv", delimiter=",")

 
.decl NullNode(x: number, y: number)

.rule
NullNode(x, y) :- NullEdge(x, y).
# Reordered: moved Edge(w, y) before NullNode(x, w) to change join order
NullNode(x, y) :- Edge(w, y), NullNode(x, w).

.printsize NullNode
