
.decl P(X: number, Z: number)
.input P(IO="file", filename="P.csv", delimiter=",")

.decl Q(X: number, Y: number, Z: number)
.input Q(IO="file", filename="Q.csv", delimiter=",")

.decl R(R: number, P: number, E: number)
.input R(IO="file", filename="R.csv", delimiter=",")

.decl C(Y: number, Z: number, W: number)
.input C(IO="file", filename="C.csv", delimiter=",")

.decl U(R: number, Z: number, W: number)
.input U(IO="file", filename="U.csv", delimiter=",")

.decl S(R: number, P: number)
.input S(IO="file", filename="S.csv", delimiter=",")

 
.decl OutP(X: number, Z: number)


.decl OutQ(X: number, Y: number, Z: number)

.rule
OutP(x,y) :- P(x,y).
OutQ(x,y,z) :- Q(x,y,z).
OutP(x,z) :- OutP(x,y), OutP(y,z).
OutQ(x,r,z) :- OutP(x,y), OutQ(y,r,z).
OutP(x,z) :- U(w,r,z), OutQ(x,r,y), OutP(y,w).          # Reordered: moved U(w,r,z) to first position, OutQ(x,r,y) second, OutP(y,w) last
OutP(x,z) :- C(y,w,z),OutP(x,w), OutP(x,y).
OutQ(x,q,z) :- OutQ(x,r,z),S(r,q).
OutQ(x,e,o) :- OutQ(x,y,z),R(y,u,e),OutQ(z,u,o).

.printsize OutP
.printsize OutQ
