
.decl Arc(x:number, y:number, l:number)
.input Arc.csv

.printsize
.decl Zero(x:number, y:number)
.decl One(x:number, y:number)
.decl Dyck(x:number, y:number)


.rule
Zero(x, y) :- Arc(x, y, 0).
One(x, y) :- Arc(x, y, 1).

Dyck(x, y) :- Zero(x, z), Zero(z, y).
Dyck(x, y) :- One(x, z), One(z, y).
Dyck(x, y) :- Dyck(z, w), Zero(w, y), Zero(x, z).       # Reordered: moved Dyck(z, w) to first position, Zero(w, y) second, Zero(x, z) last
Dyck(x, y) :- One(x, z), Dyck(z, w), One(w, y).
Dyck(x, y) :- Dyck(x, z), Dyck(z, y).
