typedef int = signed<32>

input relation Source(id: int)
input relation Arc(x: int, y: int)

output relation BipartiteViolation(x: int)
output relation Zero(x: int)
output relation MOne(x: int)
output relation BiArc(x: int, y: int)

BiArc(x, y) :- Arc(x, y).
BiArc(x, y) :- Arc(y, x).
Zero(x) :- Source(x).
MOne(y) :- BiArc(x, y), Zero(x).
Zero(y) :- BiArc(x, y), MOne(x).
BipartiteViolation(x) :- MOne(x), Zero(x).

output relation RelationSizes(rel: string, size:bit<64>)
RelationSizes("Zero", size) :- Zero(x),  var size = (x).group_by(()).count_distinct().
RelationSizes("MOne", size) :- MOne(x),  var size = (x).group_by(()).count_distinct().
RelationSizes("BipartiteViolation", size) :- BipartiteViolation(x),  var size = (x).group_by(()).count_distinct().