typedef node = signed<32>

input relation Arc(x: node, y: node) 

relation Cc3(x: node, y: node)
relation Cc2(x: node, y: node)

output relation Cc(x: node) 

Cc3(x, min_x) :- Arc(x, _), var min_x = Aggregate((x), group_min(x)).
Cc3(y, min_z) :- Cc3(x, z), Arc(x, y), var min_z = Aggregate((y), group_min(z)).
Cc2(x, min_y) :- Cc3(x,y), var min_y = Aggregate((x), group_min(y)).
Cc(x) :- Cc2(_, x).

 
