typedef node = signed<32>

input relation Arc(x: node, y: node) 

relation CC3(x: node, y: node)
relation CC2(x: node, y: node)

output relation CC(x: node) 

CC3(x, min_x) :- Arc(x, _), var min_x = Aggregate((x), group_min(x)).
CC3(y, min_z) :- CC3(x, z), Arc(x, y), var min_z = Aggregate((y), group_min(z)).
CC2(x, min_y) :- CC3(x,y), var min_y = Aggregate((x), group_min(y)).
CC(x) :- CC2(_, x).

output relation RelationSizes(rel: string, size:bit<64>)
RelationSizes("CC", size) :- CC(x),  var size = (x).group_by(()).count_distinct().