typedef node = signed<32>
typedef label = signed<32>

input relation Arc(x: node, y: node, l: label)

relation Zero(x: node, y: node)
relation MOne(x: node, y: node)
output relation Dyck(x: node, y: node)

Zero(x, y) :- Arc(x, y, 0).
MOne(x, y) :- Arc(x, y, 1).

Dyck(x, y) :- Zero(x, z), Zero(z, y).
Dyck(x, y) :- MOne(x, z), MOne(z, y).
Dyck(x, y) :- Zero(x, z), Dyck(z, w), Zero(w, y).
Dyck(x, y) :- MOne(w, y), Dyck(z, w), MOne(x, z).
Dyck(x, y) :- Dyck(x, z), Dyck(z, y).

output relation RelationSizes(rel: string, size: bit<64>)
RelationSizes("Dyck", size) :- Dyck(x, y),  var size = (x, y).group_by(()).count_distinct().