typedef node = signed<32>

input relation P(X: node, Z: node)
input relation Q(X: node, Y: node, Z: node)
input relation R(R: node, P: node, E: node)
input relation C(Y: node, Z: node, W: node)
input relation U(R: node, Z: node, W: node)
input relation S(R: node, P: node)

output relation OutP(X: node, Z: node)
output relation OutQ(X: node, Y: node, Z: node)
output relation RelationSizes(relation_name: string, size: bit<64>)

OutP(x,y) :- P(x,y).
OutQ(x,y,z) :- Q(x,y,z).
OutP(x,z) :- OutP(x,y), OutP(y,z).
OutQ(x,r,z) :- OutP(x,y), OutQ(y,r,z).
OutP(x,z) :- OutP(y,w), U(w,r,z), OutQ(x,r,y).
OutP(x,z) :- C(y,w,z),OutP(x,w), OutP(x,y).
OutQ(x,q,z) :- OutQ(x,r,z),S(r,q).
OutQ(x,e,o) :- R(y,u,e),OutQ(z,u,o),OutQ(x,y,z).

RelationSizes("OutP", size) :- size = Aggregate((), count_distinct(OutP(x, z))).
RelationSizes("OutQ", size) :- size = Aggregate((), count_distinct(OutQ(x, y, z))).