typedef node = signed<32>
typedef weight = signed<32>

input relation Arc(src: node, dest: node, weight: weight)
input relation Source(src: node)

relation SSSP2(x: node, y: weight)
output relation SSSP(x: node, y: weight)

SSSP2(x, min_weight) :- Source(x), var min_weight = Aggregate((x), group_min(0)).
SSSP2(y, min_dist) :- Arc(x, y, d2), SSSP2(x, d1), var min_dist = Aggregate((y), group_min(d1 + d2)).
SSSP(x, min_d) :- SSSP2(x, d), var min_d = Aggregate((x), group_min(d)).

output relation RelationSizes(rel: string, size: bit<64>)
RelationSizes("SSSP", size) :- SSSP(x, y),  var size = (x, y).group_by(()).count_distinct().