
.in
.decl P(X: number, Z: number)
.input P.csv
.decl Q(X: number, Y: number, Z: number)
.input Q.csv
.decl R(R: number, P: number, E: number)
.input R.csv
.decl C(Y: number, Z: number, W: number)
.input C.csv
.decl U(R: number, Z: number, W: number)
.input U.csv
.decl S(R: number, P: number)
.input S.csv
.printsize
.decl OutP(X: number, Z: number)
.printsize
.decl OutQ(X: number, Y: number, Z: number)

.rule
OutP(x, y) :- P(x, y).
OutQ(x, y, z) :- Q(x, y, z).
OutP(x, z) :- OutP(y, z), OutP(x, y).
OutQ(x, r, z) :- OutQ(y, r, z), OutP(x, y).
OutP(x, z) :- OutQ(x, r, y), U(w, r, z), OutP(y, w).
.optimize
OutP(x, z) :- OutP(x, y), OutP(x, w), C(y, w, z).
OutQ(x, q, z) :- OutQ(x, r, z), S(r, q).
OutQ(x, e, o) :- OutQ(x, y, z), R(y, u, e), OutQ(z, u, o).
