sed "s/\<abi_intrinsic\>/Abi_intrinsic/g" -i z3.dl
sed "s/\<address_array_aux\>/Address_array_aux/g" -i z3.dl
sed "s/\<address_array\>/Address_array/g" -i z3.dl
sed "s/\<address_in_data_refined\>/Address_in_data_refined/g" -i z3.dl
sed "s/\<address_in_data_refined_range_in_ea\>/Address_in_data_refined_range_in_ea/g" -i z3.dl
sed "s/\<addr_outside_section_used_for_memory_access\>/Addr_outside_section_used_for_memory_access/g" -i z3.dl
sed "s/\<adjusts_stack_in_block\>/Adjusts_stack_in_block/g" -i z3.dl
sed "s/\<after_address_in_data\>/After_address_in_data/g" -i z3.dl
sed "s/\<after_end\>/After_end/g" -i z3.dl
sed "s/\<aligned_address_in_data\>/Aligned_address_in_data/g" -i z3.dl
sed "s/\<alignment_candidate\>/Alignment_candidate/g" -i z3.dl
sed "s/\<alignment\>/Alignment/g" -i z3.dl
sed "s/\<ambiguous_symbol\>/Ambiguous_symbol/g" -i z3.dl
sed "s/\<arch_alignment_required\>/Arch_alignment_required/g" -i z3.dl
sed "s/\<arch_call\>/Arch_call/g" -i z3.dl
sed "s/\<arch_call_operation\>/Arch_call_operation/g" -i z3.dl
sed "s/\<arch_call_operation_op_index\>/Arch_call_operation_op_index/g" -i z3.dl
sed "s/\<arch_cmp_operation\>/Arch_cmp_operation/g" -i z3.dl
sed "s/\<arch_cmp_zero_operation\>/Arch_cmp_zero_operation/g" -i z3.dl
sed "s/\<arch_conditional\>/Arch_conditional/g" -i z3.dl
sed "s/\<arch_conditional_operation\>/Arch_conditional_operation/g" -i z3.dl
sed "s/\<arch_condition_flags_reg\>/Arch_condition_flags_reg/g" -i z3.dl
sed "s/\<arch_data_access_size\>/Arch_data_access_size/g" -i z3.dl
sed "s/\<arch_extend_load\>/Arch_extend_load/g" -i z3.dl
sed "s/\<arch_extend_reg\>/Arch_extend_reg/g" -i z3.dl
sed "s/\<arch_frame_pointer\>/Arch_frame_pointer/g" -i z3.dl
sed "s/\<arch_general_purpose_reg\>/Arch_general_purpose_reg/g" -i z3.dl
sed "s/\<arch_halt_operation\>/Arch_halt_operation/g" -i z3.dl
sed "s/\<arch_instruction_at\>/Arch_instruction_at/g" -i z3.dl
sed "s/\<arch_integer_reg_param\>/Arch_integer_reg_param/g" -i z3.dl
sed "s/\<arch_interrupt_operation\>/Arch_interrupt_operation/g" -i z3.dl
sed "s/\<arch_is_nop\>/Arch_is_nop/g" -i z3.dl
sed "s/\<arch_jump_condition_code\>/Arch_jump_condition_code/g" -i z3.dl
sed "s/\<arch_jump\>/Arch_jump/g" -i z3.dl
sed "s/\<arch_jump_operation\>/Arch_jump_operation/g" -i z3.dl
sed "s/\<arch_jump_operation_op_index\>/Arch_jump_operation_op_index/g" -i z3.dl
sed "s/\<arch_logic_operation\>/Arch_logic_operation/g" -i z3.dl
sed "s/\<arch_loop_operation\>/Arch_loop_operation/g" -i z3.dl
sed "s/\<arch_loop_prefix\>/Arch_loop_prefix/g" -i z3.dl
sed "s/\<arch_memory_access\>/Arch_memory_access/g" -i z3.dl
sed "s/\<arch_memory_access_truncate\>/Arch_memory_access_truncate/g" -i z3.dl
sed "s/\<arch_move_operation\>/Arch_move_operation/g" -i z3.dl
sed "s/\<arch_move_reg_imm\>/Arch_move_reg_imm/g" -i z3.dl
sed "s/\<arch_move_reg_reg\>/Arch_move_reg_reg/g" -i z3.dl
sed "s/\<arch_multiplication_operation\>/Arch_multiplication_operation/g" -i z3.dl
sed "s/\<arch_operation_alignment_required\>/Arch_operation_alignment_required/g" -i z3.dl
sed "s/\<arch_pc_relative_addr\>/Arch_pc_relative_addr/g" -i z3.dl
sed "s/\<arch_reg_arithmetic_operation\>/Arch_reg_arithmetic_operation/g" -i z3.dl
sed "s/\<arch_register_size_bytes\>/Arch_register_size_bytes/g" -i z3.dl
sed "s/\<arch_reg_map_rule\>/Arch_reg_map_rule/g" -i z3.dl
sed "s/\<arch_reg_reg_arithmetic_operation\>/Arch_reg_reg_arithmetic_operation/g" -i z3.dl
sed "s/\<arch_reg_relative_load\>/Arch_reg_relative_load/g" -i z3.dl
sed "s/\<arch_return\>/Arch_return/g" -i z3.dl
sed "s/\<arch_return_operation\>/Arch_return_operation/g" -i z3.dl
sed "s/\<arch_return_reg\>/Arch_return_reg/g" -i z3.dl
sed "s/\<arch_shift_rotate_operation\>/Arch_shift_rotate_operation/g" -i z3.dl
sed "s/\<arch_simple_data_load\>/Arch_simple_data_load/g" -i z3.dl
sed "s/\<arch_stack_pointer\>/Arch_stack_pointer/g" -i z3.dl
sed "s/\<arch_store_immediate\>/Arch_store_immediate/g" -i z3.dl
sed "s/\<arch_syscall_operation\>/Arch_syscall_operation/g" -i z3.dl
sed "s/\<avoid_symbols\>/Avoid_symbols/g" -i z3.dl
sed "s/\<bad_symbol_constant\>/Bad_symbol_constant/g" -i z3.dl
sed "s/\<base_relative_jump\>/Base_relative_jump/g" -i z3.dl
sed "s/\<base_relative_operand\>/Base_relative_operand/g" -i z3.dl
sed "s/\<base_relative_operation\>/Base_relative_operation/g" -i z3.dl
sed "s/\<base_relative_symbolic_operand\>/Base_relative_symbolic_operand/g" -i z3.dl
sed "s/\<basic_reg_def_use_def\>/Basic_reg_def_use_def/g" -i z3.dl
sed "s/\<basic_reg_def_use_used\>/Basic_reg_def_use_used/g" -i z3.dl
sed "s/\<basic_reg_def_use_used_explicit\>/Basic_reg_def_use_used_explicit/g" -i z3.dl
sed "s/\<basic_target\>/Basic_target/g" -i z3.dl
sed "s/\<best_func_symbol\>/Best_func_symbol/g" -i z3.dl
sed "s/\<best_ifunc_symbol\>/Best_ifunc_symbol/g" -i z3.dl
sed "s/\<best_symexpr_symbol\>/Best_symexpr_symbol/g" -i z3.dl
sed "s/\<best_value_reg\>/Best_value_reg/g" -i z3.dl
sed "s/\<block_boundaries\>/Block_boundaries/g" -i z3.dl
sed "s/\<block_candidate_boundaries\>/Block_candidate_boundaries/g" -i z3.dl
sed "s/\<block_candidate_dependency_edge\>/Block_candidate_dependency_edge/g" -i z3.dl
sed "s/\<block\>/Block/g" -i z3.dl
sed "s/\<block_has_non_nop\>/Block_has_non_nop/g" -i z3.dl
sed "s/\<block_heuristic\>/Block_heuristic/g" -i z3.dl
sed "s/\<block_implies_block\>/Block_implies_block/g" -i z3.dl
sed "s/\<block_information\>/Block_information/g" -i z3.dl
sed "s/\<block_instruction_next\>/Block_instruction_next/g" -i z3.dl
sed "s/\<block_last_instruction\>/Block_last_instruction/g" -i z3.dl
sed "s/\<block_limit\>/Block_limit/g" -i z3.dl
sed "s/\<block_needs_merging\>/Block_needs_merging/g" -i z3.dl
sed "s/\<block_needs_splitting_at\>/Block_needs_splitting_at/g" -i z3.dl
sed "s/\<block_next\>/Block_next/g" -i z3.dl
sed "s/\<block_overlap\>/Block_overlap/g" -i z3.dl
sed "s/\<block_points\>/Block_points/g" -i z3.dl
sed "s/\<block_points_proportional\>/Block_points_proportional/g" -i z3.dl
sed "s/\<block_still_overlap\>/Block_still_overlap/g" -i z3.dl
sed "s/\<block_total_points\>/Block_total_points/g" -i z3.dl
sed "s/\<boundary_sym_expr\>/Boundary_sym_expr/g" -i z3.dl
sed "s/\<bss_data\>/Bss_data/g" -i z3.dl
sed "s/\<bss_section\>/Bss_section/g" -i z3.dl
sed "s/\<bss_section_limits\>/Bss_section_limits/g" -i z3.dl
sed "s/\<call_tls_get_addr\>/Call_tls_get_addr/g" -i z3.dl
sed "s/\<candidate_block_is_not_padding\>/Candidate_block_is_not_padding/g" -i z3.dl
sed "s/\<candidate_block_is_padding\>/Candidate_block_is_padding/g" -i z3.dl
sed "s/\<cfg_edge\>/Cfg_edge/g" -i z3.dl
sed "s/\<cfg_edge_to_symbol\>/Cfg_edge_to_symbol/g" -i z3.dl
sed "s/\<cfg_edge_to_top\>/Cfg_edge_to_top/g" -i z3.dl
sed "s/\<cfi_directive\>/Cfi_directive/g" -i z3.dl
sed "s/\<cfi_operand_is_register\>/Cfi_operand_is_register/g" -i z3.dl
sed "s/\<cmp_defines\>/Cmp_defines/g" -i z3.dl
sed "s/\<cmp_immediate_to_reg\>/Cmp_immediate_to_reg/g" -i z3.dl
sed "s/\<cmp_reg_to_reg\>/Cmp_reg_to_reg/g" -i z3.dl
sed "s/\<code_in_block_candidate\>/Code_in_block_candidate/g" -i z3.dl
sed "s/\<code_in_block_candidate_refined\>/Code_in_block_candidate_refined/g" -i z3.dl
sed "s/\<code_in_block\>/Code_in_block/g" -i z3.dl
sed "s/\<code_in_refined_block\>/Code_in_refined_block/g" -i z3.dl
sed "s/\<code_in_split_block\>/Code_in_split_block/g" -i z3.dl
sed "s/\<code_pointer_in_data\>/Code_pointer_in_data/g" -i z3.dl
sed "s/\<code_section\>/Code_section/g" -i z3.dl
sed "s/\<common_tail\>/Common_tail/g" -i z3.dl
sed "s/\<compare_and_jump_immediate\>/Compare_and_jump_immediate/g" -i z3.dl
sed "s/\<compare_and_jump_indirect\>/Compare_and_jump_indirect/g" -i z3.dl
sed "s/\<compare_and_jump_indirect_op_valid\>/Compare_and_jump_indirect_op_valid/g" -i z3.dl
sed "s/\<compare_and_jump_register\>/Compare_and_jump_register/g" -i z3.dl
sed "s/\<composite_data_access\>/Composite_data_access/g" -i z3.dl
sed "s/\<conditional_jump\>/Conditional_jump/g" -i z3.dl
sed "s/\<conditional_return\>/Conditional_return/g" -i z3.dl
sed "s/\<const_value_reg_used\>/Const_value_reg_used/g" -i z3.dl
sed "s/\<copy_relocated_symbol\>/Copy_relocated_symbol/g" -i z3.dl
sed "s/\<correlated_live_reg\>/Correlated_live_reg/g" -i z3.dl
sed "s/\<dap_location\>/Dap_location/g" -i z3.dl
sed "s/\<dap_max_mult\>/Dap_max_mult/g" -i z3.dl
sed "s/\<data_access\>/Data_access/g" -i z3.dl
sed "s/\<data_access_limit\>/Data_access_limit/g" -i z3.dl
sed "s/\<data_access_pattern_candidate\>/Data_access_pattern_candidate/g" -i z3.dl
sed "s/\<data_access_pattern_candidate_refined\>/Data_access_pattern_candidate_refined/g" -i z3.dl
sed "s/\<data_access_pattern\>/Data_access_pattern/g" -i z3.dl
sed "s/\<data_access_pattern_non_zero\>/Data_access_pattern_non_zero/g" -i z3.dl
sed "s/\<data_block_candidate\>/Data_block_candidate/g" -i z3.dl
sed "s/\<data_in_code\>/Data_in_code/g" -i z3.dl
sed "s/\<data_in_code_propagate\>/Data_in_code_propagate/g" -i z3.dl
sed "s/\<data_limit_after_access\>/Data_limit_after_access/g" -i z3.dl
sed "s/\<data_limit\>/Data_limit/g" -i z3.dl
sed "s/\<data_object_boundary\>/Data_object_boundary/g" -i z3.dl
sed "s/\<data_object_candidate\>/Data_object_candidate/g" -i z3.dl
sed "s/\<data_object_conflict\>/Data_object_conflict/g" -i z3.dl
sed "s/\<data_object\>/Data_object/g" -i z3.dl
sed "s/\<data_object_point\>/Data_object_point/g" -i z3.dl
sed "s/\<data_object_total_points\>/Data_object_total_points/g" -i z3.dl
sed "s/\<data_section\>/Data_section/g" -i z3.dl
sed "s/\<data_segment\>/Data_segment/g" -i z3.dl
sed "s/\<default_heuristic_weight\>/Default_heuristic_weight/g" -i z3.dl
sed "s/\<defined_symbol\>/Defined_symbol/g" -i z3.dl
sed "s/\<def_register_is_not_base_address\>/Def_register_is_not_base_address/g" -i z3.dl
sed "s/\<def_used_for_address\>/Def_used_for_address/g" -i z3.dl
sed "s/\<dest_enlarged_data_section\>/Dest_enlarged_data_section/g" -i z3.dl
sed "s/\<direct_call\>/Direct_call/g" -i z3.dl
sed "s/\<direct_jump\>/Direct_jump/g" -i z3.dl
sed "s/\<direct_or_pcrel_jump\>/Direct_or_pcrel_jump/g" -i z3.dl
sed "s/\<discarded_block\>/Discarded_block/g" -i z3.dl
sed "s/\<discarded_data_object\>/Discarded_data_object/g" -i z3.dl
sed "s/\<discarded_jump_table_entry\>/Discarded_jump_table_entry/g" -i z3.dl
sed "s/\<dwarf_encoding_size\>/Dwarf_encoding_size/g" -i z3.dl
sed "s/\<dwarf_to_cfi\>/Dwarf_to_cfi/g" -i z3.dl
sed "s/\<elf_avoid_symbols\>/Elf_avoid_symbols/g" -i z3.dl
sed "s/\<elf_pointer_array_section_type\>/Elf_pointer_array_section_type/g" -i z3.dl
sed "s/\<elf_relocation_size\>/Elf_relocation_size/g" -i z3.dl
sed "s/\<elf_section_type\>/Elf_section_type/g" -i z3.dl
sed "s/\<endproc_local_index\>/Endproc_local_index/g" -i z3.dl
sed "s/\<entry_point\>/Entry_point/g" -i z3.dl
sed "s/\<exception_section\>/Exception_section/g" -i z3.dl
sed "s/\<false_negative\>/False_negative/g" -i z3.dl
sed "s/\<false_positive\>/False_positive/g" -i z3.dl
sed "s/\<fde_addresses\>/Fde_addresses/g" -i z3.dl
sed "s/\<fde_block_addresses\>/Fde_block_addresses/g" -i z3.dl
sed "s/\<fde_instruction_block_offset\>/Fde_instruction_block_offset/g" -i z3.dl
sed "s/\<fde_instruction_ref\>/Fde_instruction_ref/g" -i z3.dl
sed "s/\<first_block_in_byte_interval\>/First_block_in_byte_interval/g" -i z3.dl
sed "s/\<first_synchronous_access\>/First_synchronous_access/g" -i z3.dl
sed "s/\<flags_and_jump_pair\>/Flags_and_jump_pair/g" -i z3.dl
sed "s/\<function_inference_function_entry\>/Function_inference_function_entry/g" -i z3.dl
sed "s/\<function_inference_function_entry_initial\>/Function_inference_function_entry_initial/g" -i z3.dl
sed "s/\<function_inference_function_entry_name\>/Function_inference_function_entry_name/g" -i z3.dl
sed "s/\<function_inference_function_without_callframe\>/Function_inference_function_without_callframe/g" -i z3.dl
sed "s/\<function_inference_in_function\>/Function_inference_in_function/g" -i z3.dl
sed "s/\<function_inference_in_function_initial\>/Function_inference_in_function_initial/g" -i z3.dl
sed "s/\<function_inference_not_in_function_initial\>/Function_inference_not_in_function_initial/g" -i z3.dl
sed "s/\<function_pointer_section\>/Function_pointer_section/g" -i z3.dl
sed "s/\<function_symbol\>/Function_symbol/g" -i z3.dl
sed "s/\<got_reference\>/Got_reference/g" -i z3.dl
sed "s/\<got_reference_pointer\>/Got_reference_pointer/g" -i z3.dl
sed "s/\<got_relative_operand\>/Got_relative_operand/g" -i z3.dl
sed "s/\<got_section\>/Got_section/g" -i z3.dl
sed "s/\<halt\>/Halt/g" -i z3.dl
sed "s/\<heuristic_weight\>/Heuristic_weight/g" -i z3.dl
sed "s/\<ifunc_scope_score\>/Ifunc_scope_score/g" -i z3.dl
sed "s/\<ifunc_symbol_score\>/Ifunc_symbol_score/g" -i z3.dl
sed "s/\<impossible_block\>/Impossible_block/g" -i z3.dl
sed "s/\<incomplete_block\>/Incomplete_block/g" -i z3.dl
sed "s/\<incremental_linking_candidate\>/Incremental_linking_candidate/g" -i z3.dl
sed "s/\<incremental_linking\>/Incremental_linking/g" -i z3.dl
sed "s/\<indirect_call\>/Indirect_call/g" -i z3.dl
sed "s/\<indirect_jump\>/Indirect_jump/g" -i z3.dl
sed "s/\<inferred_main_dispatch\>/Inferred_main_dispatch/g" -i z3.dl
sed "s/\<inferred_main_function\>/Inferred_main_function/g" -i z3.dl
sed "s/\<inferred_main_in_reg\>/Inferred_main_in_reg/g" -i z3.dl
sed "s/\<inferred_special_symbol\>/Inferred_special_symbol/g" -i z3.dl
sed "s/\<inferred_symbol\>/Inferred_symbol/g" -i z3.dl
sed "s/\<initialized_data_segment\>/Initialized_data_segment/g" -i z3.dl
sed "s/\<instruction\>/Instruction/g" -i z3.dl
sed "s/\<instruction_displacement_offset\>/Instruction_displacement_offset/g" -i z3.dl
sed "s/\<instruction_get_dest_op\>/Instruction_get_dest_op/g" -i z3.dl
sed "s/\<instruction_get_op\>/Instruction_get_op/g" -i z3.dl
sed "s/\<instruction_get_src_op\>/Instruction_get_src_op/g" -i z3.dl
sed "s/\<instruction_has_loop_prefix\>/Instruction_has_loop_prefix/g" -i z3.dl
sed "s/\<instruction_has_relocation\>/Instruction_has_relocation/g" -i z3.dl
sed "s/\<instruction_immediate_offset\>/Instruction_immediate_offset/g" -i z3.dl
sed "s/\<instruction_memory_access_size\>/Instruction_memory_access_size/g" -i z3.dl
sed "s/\<inter_procedural_edge\>/Inter_procedural_edge/g" -i z3.dl
sed "s/\<interval_schedule_tie\>/Interval_schedule_tie/g" -i z3.dl
sed "s/\<invalid\>/Invalid/g" -i z3.dl
sed "s/\<is_padding\>/Is_padding/g" -i z3.dl
sed "s/\<is_xor_reset\>/Is_xor_reset/g" -i z3.dl
sed "s/\<jump_table\>/Jump_table/g" -i z3.dl
sed "s/\<jump_table_element_access\>/Jump_table_element_access/g" -i z3.dl
sed "s/\<jump_table_max\>/Jump_table_max/g" -i z3.dl
sed "s/\<jump_table_prelude\>/Jump_table_prelude/g" -i z3.dl
sed "s/\<jump_table_signed\>/Jump_table_signed/g" -i z3.dl
sed "s/\<jump_table_start\>/Jump_table_start/g" -i z3.dl
sed "s/\<jump_table_target\>/Jump_table_target/g" -i z3.dl
sed "s/\<known_block\>/Known_block/g" -i z3.dl
sed "s/\<label_conflict\>/Label_conflict/g" -i z3.dl
sed "s/\<labeled_data_candidate\>/Labeled_data_candidate/g" -i z3.dl
sed "s/\<labeled_ea\>/Labeled_ea/g" -i z3.dl
sed "s/\<last_fde\>/Last_fde/g" -i z3.dl
sed "s/\<last_fde_instruction\>/Last_fde_instruction/g" -i z3.dl
sed "s/\<last_value_reg_limit\>/Last_value_reg_limit/g" -i z3.dl
sed "s/\<likely_fallthrough\>/Likely_fallthrough/g" -i z3.dl
sed "s/\<limit_reg_op\>/Limit_reg_op/g" -i z3.dl
sed "s/\<limit_type_map\>/Limit_type_map/g" -i z3.dl
sed "s/\<loaded_section\>/Loaded_section/g" -i z3.dl
sed "s/\<low_pass_filter\>/Low_pass_filter/g" -i z3.dl
sed "s/\<low_pass_mask\>/Low_pass_mask/g" -i z3.dl
sed "s/\<lsda_callsite_addresses\>/Lsda_callsite_addresses/g" -i z3.dl
sed "s/\<lsda_symbol_minus_symbol\>/Lsda_symbol_minus_symbol/g" -i z3.dl
sed "s/\<main_function\>/Main_function/g" -i z3.dl
sed "s/\<max_instruction_size\>/Max_instruction_size/g" -i z3.dl
sed "s/\<may_fallthrough\>/May_fallthrough/g" -i z3.dl
sed "s/\<may_have_symbolic_immediate\>/May_have_symbolic_immediate/g" -i z3.dl
sed "s/\<merged_data_region\>/Merged_data_region/g" -i z3.dl
sed "s/\<misaligned_fde_start\>/Misaligned_fde_start/g" -i z3.dl
sed "s/\<missed_jump_table\>/Missed_jump_table/g" -i z3.dl
sed "s/\<missing_relocation_handling\>/Missing_relocation_handling/g" -i z3.dl
sed "s/\<missing_weight\>/Missing_weight/g" -i z3.dl
sed "s/\<moved_data_label\>/Moved_data_label/g" -i z3.dl
sed "s/\<moved_displacement_candidate\>/Moved_displacement_candidate/g" -i z3.dl
sed "s/\<moved_immediate_candidate\>/Moved_immediate_candidate/g" -i z3.dl
sed "s/\<moved_label_candidate\>/Moved_label_candidate/g" -i z3.dl
sed "s/\<moved_label_class\>/Moved_label_class/g" -i z3.dl
sed "s/\<moved_label\>/Moved_label/g" -i z3.dl
sed "s/\<moved_pc_relative_candidate\>/Moved_pc_relative_candidate/g" -i z3.dl
sed "s/\<must_fallthrough\>/Must_fallthrough/g" -i z3.dl
sed "s/\<negative_block_heuristic\>/Negative_block_heuristic/g" -i z3.dl
sed "s/\<next_address_in_data\>/Next_address_in_data/g" -i z3.dl
sed "s/\<next_block_in_byte_interval\>/Next_block_in_byte_interval/g" -i z3.dl
sed "s/\<next\>/Next/g" -i z3.dl
sed "s/\<next_data_access\>/Next_data_access/g" -i z3.dl
sed "s/\<next_data_limit\>/Next_data_limit/g" -i z3.dl
sed "s/\<next_dyssynchronous_data_access\>/Next_dyssynchronous_data_access/g" -i z3.dl
sed "s/\<next_end\>/Next_end/g" -i z3.dl
sed "s/\<next_refined_block_in_byte_interval\>/Next_refined_block_in_byte_interval/g" -i z3.dl
sed "s/\<next_start\>/Next_start/g" -i z3.dl
sed "s/\<next_type\>/Next_type/g" -i z3.dl
sed "s/\<non_zero_data_section\>/Non_zero_data_section/g" -i z3.dl
sed "s/\<nop_block\>/Nop_block/g" -i z3.dl
sed "s/\<nop_in_padding_candidate\>/Nop_in_padding_candidate/g" -i z3.dl
sed "s/\<no_return_block\>/No_return_block/g" -i z3.dl
sed "s/\<no_return_call\>/No_return_call/g" -i z3.dl
sed "s/\<no_return_call_propagated\>/No_return_call_propagated/g" -i z3.dl
sed "s/\<no_return_call_refined\>/No_return_call_refined/g" -i z3.dl
sed "s/\<no_return_function\>/No_return_function/g" -i z3.dl
sed "s/\<no_value_reg_limit\>/No_value_reg_limit/g" -i z3.dl
sed "s/\<npad\>/Npad/g" -i z3.dl
sed "s/\<op_immediate_and_reg\>/Op_immediate_and_reg/g" -i z3.dl
sed "s/\<op_immediate\>/Op_immediate/g" -i z3.dl
sed "s/\<op_indirect_contains_reg\>/Op_indirect_contains_reg/g" -i z3.dl
sed "s/\<op_indirect\>/Op_indirect/g" -i z3.dl
sed "s/\<op_indirect_mapped\>/Op_indirect_mapped/g" -i z3.dl
sed "s/\<op_regdirect_contains_reg\>/Op_regdirect_contains_reg/g" -i z3.dl
sed "s/\<overlapping_instruction\>/Overlapping_instruction/g" -i z3.dl
sed "s/\<padding_block_candidate\>/Padding_block_candidate/g" -i z3.dl
sed "s/\<padding_block_limit\>/Padding_block_limit/g" -i z3.dl
sed "s/\<padding\>/Padding/g" -i z3.dl
sed "s/\<pc_load_call\>/Pc_load_call/g" -i z3.dl
sed "s/\<pc_relative_call\>/Pc_relative_call/g" -i z3.dl
sed "s/\<pc_relative_jump\>/Pc_relative_jump/g" -i z3.dl
sed "s/\<pc_relative_operand\>/Pc_relative_operand/g" -i z3.dl
sed "s/\<pe_exception_handler\>/Pe_exception_handler/g" -i z3.dl
sed "s/\<pe_load_config\>/Pe_load_config/g" -i z3.dl
sed "s/\<pe_relocation_size\>/Pe_relocation_size/g" -i z3.dl
sed "s/\<plt_block\>/Plt_block/g" -i z3.dl
sed "s/\<plt_entry\>/Plt_entry/g" -i z3.dl
sed "s/\<plt_section\>/Plt_section/g" -i z3.dl
sed "s/\<pointer_to_external_symbol\>/Pointer_to_external_symbol/g" -i z3.dl
sed "s/\<possible_rva_operand\>/Possible_rva_operand/g" -i z3.dl
sed "s/\<possible_target\>/Possible_target/g" -i z3.dl
sed "s/\<possible_target_from\>/Possible_target_from/g" -i z3.dl
sed "s/\<preferred_data_access\>/Preferred_data_access/g" -i z3.dl
sed "s/\<refined_block\>/Refined_block/g" -i z3.dl
sed "s/\<refined_block_last_instruction\>/Refined_block_last_instruction/g" -i z3.dl
sed "s/\<reg_call\>/Reg_call/g" -i z3.dl
sed "s/\<reg_def_use_ambiguous_block_last_def\>/Reg_def_use_ambiguous_block_last_def/g" -i z3.dl
sed "s/\<reg_def_use_ambiguous_last_def_in_block\>/Reg_def_use_ambiguous_last_def_in_block/g" -i z3.dl
sed "s/\<reg_def_use_block_last_def\>/Reg_def_use_block_last_def/g" -i z3.dl
sed "s/\<reg_def_use_def\>/Reg_def_use_def/g" -i z3.dl
sed "s/\<reg_def_use_defined_in_block\>/Reg_def_use_defined_in_block/g" -i z3.dl
sed "s/\<reg_def_use_def_used\>/Reg_def_use_def_used/g" -i z3.dl
sed "s/\<reg_def_use_flow_def\>/Reg_def_use_flow_def/g" -i z3.dl
sed "s/\<reg_def_use_last_def_in_block\>/Reg_def_use_last_def_in_block/g" -i z3.dl
sed "s/\<reg_def_use_live_var_at_block_end\>/Reg_def_use_live_var_at_block_end/g" -i z3.dl
sed "s/\<reg_def_use_live_var_at_prior_used\>/Reg_def_use_live_var_at_prior_used/g" -i z3.dl
sed "s/\<reg_def_use_live_var_def\>/Reg_def_use_live_var_def/g" -i z3.dl
sed "s/\<reg_def_use_live_var_used\>/Reg_def_use_live_var_used/g" -i z3.dl
sed "s/\<reg_def_use_ref_in_block\>/Reg_def_use_ref_in_block/g" -i z3.dl
sed "s/\<reg_def_use_return_block_end\>/Reg_def_use_return_block_end/g" -i z3.dl
sed "s/\<reg_def_use_return_val_used\>/Reg_def_use_return_val_used/g" -i z3.dl
sed "s/\<reg_def_use_used\>/Reg_def_use_used/g" -i z3.dl
sed "s/\<reg_def_use_used_explicit\>/Reg_def_use_used_explicit/g" -i z3.dl
sed "s/\<reg_def_use_used_in_block\>/Reg_def_use_used_in_block/g" -i z3.dl
sed "s/\<reg_has_base_image\>/Reg_has_base_image/g" -i z3.dl
sed "s/\<reg_has_got\>/Reg_has_got/g" -i z3.dl
sed "s/\<reg_jump\>/Reg_jump/g" -i z3.dl
sed "s/\<reg_map\>/Reg_map/g" -i z3.dl
sed "s/\<reg_map_nullable\>/Reg_map_nullable/g" -i z3.dl
sed "s/\<reg_reg_arithmetic_operation_defs\>/Reg_reg_arithmetic_operation_defs/g" -i z3.dl
sed "s/\<regular_data_section\>/Regular_data_section/g" -i z3.dl
sed "s/\<reg_used_for\>/Reg_used_for/g" -i z3.dl
sed "s/\<relative_address\>/Relative_address/g" -i z3.dl
sed "s/\<relative_address_start\>/Relative_address_start/g" -i z3.dl
sed "s/\<relative_jump_table_entry_candidate\>/Relative_jump_table_entry_candidate/g" -i z3.dl
sed "s/\<relative_jump_table_entry\>/Relative_jump_table_entry/g" -i z3.dl
sed "s/\<relocation_active_symbol_table\>/Relocation_active_symbol_table/g" -i z3.dl
sed "s/\<relocation_adjustment\>/Relocation_adjustment/g" -i z3.dl
sed "s/\<relocation_adjustment_total\>/Relocation_adjustment_total/g" -i z3.dl
sed "s/\<relocation_in_operand\>/Relocation_in_operand/g" -i z3.dl
sed "s/\<relocation_size\>/Relocation_size/g" -i z3.dl
sed "s/\<reloc_type_nameless\>/Reloc_type_nameless/g" -i z3.dl
sed "s/\<reloc_type_relpc\>/Reloc_type_relpc/g" -i z3.dl
sed "s/\<reloc_type_with_name\>/Reloc_type_with_name/g" -i z3.dl
sed "s/\<resolved_reaches\>/Resolved_reaches/g" -i z3.dl
sed "s/\<resolved_transfer\>/Resolved_transfer/g" -i z3.dl
sed "s/\<resolved_transfer_to_symbol\>/Resolved_transfer_to_symbol/g" -i z3.dl
sed "s/\<segment_target_range\>/Segment_target_range/g" -i z3.dl
sed "s/\<self_contained_segment\>/Self_contained_segment/g" -i z3.dl
sed "s/\<simple_data_access_pattern\>/Simple_data_access_pattern/g" -i z3.dl
sed "s/\<special_data_section\>/Special_data_section/g" -i z3.dl
sed "s/\<special_encoding\>/Special_encoding/g" -i z3.dl
sed "s/\<split_block\>/Split_block/g" -i z3.dl
sed "s/\<stack_base_reg_move\>/Stack_base_reg_move/g" -i z3.dl
sed "s/\<stack_def_use_block_last_def\>/Stack_def_use_block_last_def/g" -i z3.dl
sed "s/\<stack_def_use_def\>/Stack_def_use_def/g" -i z3.dl
sed "s/\<stack_def_use_defined_in_block\>/Stack_def_use_defined_in_block/g" -i z3.dl
sed "s/\<stack_def_use_def_used\>/Stack_def_use_def_used/g" -i z3.dl
sed "s/\<stack_def_use_last_def_in_block\>/Stack_def_use_last_def_in_block/g" -i z3.dl
sed "s/\<stack_def_use_live_var_at_block_end\>/Stack_def_use_live_var_at_block_end/g" -i z3.dl
sed "s/\<stack_def_use_live_var_at_prior_used\>/Stack_def_use_live_var_at_prior_used/g" -i z3.dl
sed "s/\<stack_def_use_live_var_def\>/Stack_def_use_live_var_def/g" -i z3.dl
sed "s/\<stack_def_use_live_var_used\>/Stack_def_use_live_var_used/g" -i z3.dl
sed "s/\<stack_def_use_live_var_used_in_block\>/Stack_def_use_live_var_used_in_block/g" -i z3.dl
sed "s/\<stack_def_use_moves_limit\>/Stack_def_use_moves_limit/g" -i z3.dl
sed "s/\<stack_def_use_ref_in_block\>/Stack_def_use_ref_in_block/g" -i z3.dl
sed "s/\<stack_def_use_used\>/Stack_def_use_used/g" -i z3.dl
sed "s/\<stack_def_use_used_in_block\>/Stack_def_use_used_in_block/g" -i z3.dl
sed "s/\<start_function\>/Start_function/g" -i z3.dl
sed "s/\<step_limit\>/Step_limit/g" -i z3.dl
sed "s/\<step_limit_small\>/Step_limit_small/g" -i z3.dl
sed "s/\<straight_line_def_used\>/Straight_line_def_used/g" -i z3.dl
sed "s/\<straight_line_last_def\>/Straight_line_last_def/g" -i z3.dl
sed "s/\<string_candidate\>/String_candidate/g" -i z3.dl
sed "s/\<string_candidate_refined\>/String_candidate_refined/g" -i z3.dl
sed "s/\<string\>/String/g" -i z3.dl
sed "s/\<symbol_at_end\>/Symbol_at_end/g" -i z3.dl
sed "s/\<symbol_at_section_end\>/Symbol_at_section_end/g" -i z3.dl
sed "s/\<symbol_before_section_beg\>/Symbol_before_section_beg/g" -i z3.dl
sed "s/\<symbolic_data\>/Symbolic_data/g" -i z3.dl
sed "s/\<symbolic_expr_attribute\>/Symbolic_expr_attribute/g" -i z3.dl
sed "s/\<symbolic_expr\>/Symbolic_expr/g" -i z3.dl
sed "s/\<symbolic_expr_from_relocation\>/Symbolic_expr_from_relocation/g" -i z3.dl
sed "s/\<symbolic_expr_symbol_minus_symbol\>/Symbolic_expr_symbol_minus_symbol/g" -i z3.dl
sed "s/\<symbolic_operand_attribute\>/Symbolic_operand_attribute/g" -i z3.dl
sed "s/\<symbolic_operand_candidate\>/Symbolic_operand_candidate/g" -i z3.dl
sed "s/\<symbolic_operand\>/Symbolic_operand/g" -i z3.dl
sed "s/\<symbolic_operand_point\>/Symbolic_operand_point/g" -i z3.dl
sed "s/\<symbol_minus_symbol_candidate\>/Symbol_minus_symbol_candidate/g" -i z3.dl
sed "s/\<symbol_minus_symbol\>/Symbol_minus_symbol/g" -i z3.dl
sed "s/\<symbol_scope_score\>/Symbol_scope_score/g" -i z3.dl
sed "s/\<symbol_score\>/Symbol_score/g" -i z3.dl
sed "s/\<symbol_set\>/Symbol_set/g" -i z3.dl
sed "s/\<symbol_special_encoding\>/Symbol_special_encoding/g" -i z3.dl
sed "s/\<symbol_type_score\>/Symbol_type_score/g" -i z3.dl
sed "s/\<symbol_visibility_score\>/Symbol_visibility_score/g" -i z3.dl
sed "s/\<synchronous_access_barrier_after_access\>/Synchronous_access_barrier_after_access/g" -i z3.dl
sed "s/\<synchronous_access_barrier\>/Synchronous_access_barrier/g" -i z3.dl
sed "s/\<synchronous_access\>/Synchronous_access/g" -i z3.dl
sed "s/\<take_address\>/Take_address/g" -i z3.dl
sed "s/\<tls_desc_call\>/Tls_desc_call/g" -i z3.dl
sed "s/\<tls_descriptor\>/Tls_descriptor/g" -i z3.dl
sed "s/\<tls_get_addr\>/Tls_get_addr/g" -i z3.dl
sed "s/\<tls_global_dynamic\>/Tls_global_dynamic/g" -i z3.dl
sed "s/\<tls_index\>/Tls_index/g" -i z3.dl
sed "s/\<tls_local_dynamic\>/Tls_local_dynamic/g" -i z3.dl
sed "s/\<tls_operand_attribute\>/Tls_operand_attribute/g" -i z3.dl
sed "s/\<tls_relative_operand\>/Tls_relative_operand/g" -i z3.dl
sed "s/\<tls_section\>/Tls_section/g" -i z3.dl
sed "s/\<tls_segment\>/Tls_segment/g" -i z3.dl
sed "s/\<tls_segment_register\>/Tls_segment_register/g" -i z3.dl
sed "s/\<track_register\>/Track_register/g" -i z3.dl
sed "s/\<trivial_relocation\>/Trivial_relocation/g" -i z3.dl
sed "s/\<type_ordering_map\>/Type_ordering_map/g" -i z3.dl
sed "s/\<unconditional_jump\>/Unconditional_jump/g" -i z3.dl
sed "s/\<unconditional_return\>/Unconditional_return/g" -i z3.dl
sed "s/\<unexpected_negative_heuristic_weight\>/Unexpected_negative_heuristic_weight/g" -i z3.dl
sed "s/\<unresolved_block\>/Unresolved_block/g" -i z3.dl
sed "s/\<unresolved_block_overlap\>/Unresolved_block_overlap/g" -i z3.dl
sed "s/\<unresolved_interval\>/Unresolved_interval/g" -i z3.dl
sed "s/\<unresolved_interval_order\>/Unresolved_interval_order/g" -i z3.dl
sed "s/\<value_reg_at_operand\>/Value_reg_at_operand/g" -i z3.dl
sed "s/\<value_reg_at_operand_loop\>/Value_reg_at_operand_loop/g" -i z3.dl
sed "s/\<value_reg\>/Value_reg/g" -i z3.dl
sed "s/\<value_reg_edge\>/Value_reg_edge/g" -i z3.dl
sed "s/\<value_reg_limit\>/Value_reg_limit/g" -i z3.dl
sed "s/\<value_reg_max_mult\>/Value_reg_max_mult/g" -i z3.dl
sed "s/\<value_reg_unsupported\>/Value_reg_unsupported/g" -i z3.dl
sed "s/\<wis_has_prior\>/Wis_has_prior/g" -i z3.dl
sed "s/\<wis_memo\>/Wis_memo/g" -i z3.dl
sed "s/\<wis_prior\>/Wis_prior/g" -i z3.dl
sed "s/\<wis_schedule\>/Wis_schedule/g" -i z3.dl
sed "s/\<wis_schedule_iter\>/Wis_schedule_iter/g" -i z3.dl
sed "s/\<zero_relocation\>/Zero_relocation/g" -i z3.dl
