.decl AddressOf(y: number, x: number)
.input AddressOf(IO="file", filename="addressOf.csv", delimiter=",")

.decl Assign(y: number, x: number)
.input Assign(IO="file", filename="assign.csv", delimiter=",")

.decl Load(y: number, x: number)
.input Load(IO="file", filename="load.csv", delimiter=",")

.decl Store(y: number, x: number)
.input Store(IO="file", filename="store.csv", delimiter=",")

.decl PointsTo(y: number, x: number)

PointsTo(y, x) :- AddressOf(y, x).
PointsTo(y, x) :- Assign(y, z), PointsTo(z, x).
PointsTo(y, w) :- Load(y, x), PointsTo(x, z), PointsTo(z, w).
PointsTo(z, w) :- Store(y, x), PointsTo(y, z), PointsTo(x, w).

.printsize PointsTo
