.decl P(X: number, Z: number)
.decl Q(X: number, Y: number, Z: number)
.decl R(R: number, P: number, E: number)
.decl C(Y: number, Z: number, W: number)
.decl U(R: number, Z: number, W: number)
.decl S(R: number, P: number)

.input P(IO="file", filename="P.csv", delimiter=",")
.input Q(IO="file", filename="Q.csv", delimiter=",")
.input R(IO="file", filename="R.csv", delimiter=",")
.input C(IO="file", filename="C.csv", delimiter=",")
.input U(IO="file", filename="U.csv", delimiter=",")
.input S(IO="file", filename="S.csv", delimiter=",")

P(?x,?z) :- P(?x,?y), P(?y,?z).
Q(?x,?r,?z) :- P(?x,?y), Q(?y,?r,?z).
P(?x,?z) :- P(?y,?w), U(?w,?r,?z), Q(?x,?r,?y).
P(?x,?z) :- C(?y,?w,?z),P(?x,?w), P(?x,?y).
Q(?x,?q,?z) :- Q(?x,?r,?z),S(?r,?q).
Q(?x,?e,?o) :- Q(?x,?y,?z),R(?y,?u,?e),Q(?z,?u,?o).

.printsize P
.printsize Q